package pojos;
// Generated Oct 9, 2019 6:10:05 PM by Hibernate Tools 4.3.1


import java.time.LocalDate;
import java.util.Date;

/**
 * Sewa generated by hbm2java
 */
public class Sewa  implements java.io.Serializable {


     private int id;
     private String nama;
     private String alamat;
     private int nomorHp;
     private int unit;
     private Date tanggalPengambilan;
     private Date tanggalPengembalian;
     private int biaya;

    public Sewa() {
    }

    public Sewa(int id, String nama, String alamat, int nomorHp, int unit, Date tanggalPengambilan, Date tanggalPengembalian, int biaya) {
       this.id = id;
       this.nama = nama;
       this.alamat = alamat;
       this.nomorHp = nomorHp;
       this.unit = unit;
       this.tanggalPengambilan = tanggalPengambilan;
       this.tanggalPengembalian = tanggalPengembalian;
       this.biaya = biaya;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public int getNomorHp() {
        return this.nomorHp;
    }
    
    public void setNomorHp(int nomorHp) {
        this.nomorHp = nomorHp;
    }
    public int getUnit() {
        return this.unit;
    }
    
    public void setUnit(int unit) {
        this.unit = unit;
    }
    public Date getTanggalPengambilan() {
        return this.tanggalPengambilan;
    }
    
    public void setTanggalPengambilan(Date tanggalPengambilan) {
        this.tanggalPengambilan = tanggalPengambilan;
    }
    public Date getTanggalPengembalian() {
        return this.tanggalPengembalian;
    }
    
    public void setTanggalPengembalian(Date tanggalPengembalian) {
        this.tanggalPengembalian = tanggalPengembalian;
    }
    public int getBiaya() {
        return this.biaya;
    }
    
    public void setBiaya(int biaya) {
        this.biaya = biaya;
    }
    public void setTanggalPengembalian(String kembali) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setTanggalPengambilan(LocalDate ambil) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }





}


